resource "github_repository_file" "pyproject" {
  for_each   = { for k, v in local.repos : k => v if contains(v.check, "python3") }
  file       = "pyproject.toml"
  content    = <<EOF
# Autogenerated by https://github.com/BarnabyShearer/meta

[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"%{for lib in lookup(each.value, "build", [])}, "${lib}"%{endfor}]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.mypy]
strict = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/types"

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = "D202,D403,E203"
max-complexity = 10

[tool.coverage.run]
branch = true
command_line = "-m pytest"
omit = [".tox/*"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider --doctest-modules -v tests"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = %{if contains(each.value.check, "python2")}py27,%{endif}py3{7,8,9,10}

[gh-actions]
python =
%{if contains(each.value.check, "python2")}    2.7: py27%{endif}
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310

[testenv]
deps =
    mypy%{if contains(each.value.check, "python2")}[python2]%{endif}
    black
    isort
    pytest
    coverage
    pep8-naming
    flake8-docstrings
    pyproject-flake8
commands =
    black --check --diff .
    isort --check --diff .
    mypy .
    pflake8 .
    coverage run
    coverage report --fail-under=100
%{if contains(each.value.check, "python2")}
[testenv:py27]
skipsdist = True
skip_install = True
deps =
    mock
    pytest
    coverage[toml]
commands =
    pip3 install build
    python3 -m build
    bash -c "python2 -m pip install dist/*.whl"
    coverage run
    coverage report --fail-under=100
%{endif}
"""
EOF
  repository = github_repository.main[each.key].name
}

resource "github_repository_file" "ci_python" {
  for_each   = { for k, v in local.repos : k => v if contains(v.check, "python3") }
  file       = ".github/workflows/ci.yml"
  content    = <<EOF
# Autogenerated by https://github.com/BarnabyShearer/meta

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [%{if contains(each.value.check, "python2")}'2.7', %{endif}'3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: $${{ matrix.python-version }}
%{if lookup(each.value, "apt", []) != []}    - run: sudo apt install -y%{for package in each.value.apt} ${package}%{endfor}
%{endif}    - run: pip install tox tox-gh-actions
    - run: tox
EOF
  repository = github_repository.main[each.key].name
}

resource "github_repository_file" "pytyped" {
  for_each   = { for k, v in local.repos : k => v if contains(v.check, "python3") }
  file       = "${replace(each.key, "-", "_")}/py.typed"
  content    = ""
  repository = github_repository.main[each.key].name
}
