#!/bin/bash

# You need to source
export DOCKER_USERNAME=barnabyshearer
export DOCKER_PASSWORD=$(getpw docker_password)
export GITHUB_TOKEN=$(getpw github_token)
export READTHEDOCS_TOKEN=$(getpw readthedocs_token)
export TF_VAR_PYPI_TOKEN=$(getpw pypi_token)

terraform "$@"
